cmake 3.18.0

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -28,8 +28,8 @@ jobs:
         which cmake
         cmake --version
         CMAKE_VER="$(cmake --version)"
-        if ! [[ "$CMAKE_VER" =~ .*"3.17.3".* ]]; then
-          echo "ASSERTION FAILED! Instead of 3.17.3, found: "
+        if ! [[ "$CMAKE_VER" =~ .*"3.18.0".* ]]; then
+          echo "ASSERTION FAILED! Instead of 3.18.0, found: "
           echo "$CMAKE_VER"
           exit -1
         fi
