cmake v3.22.2

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -34,8 +34,8 @@ jobs:
         which cmake
         cmake --version
         CMAKE_VER="$(cmake --version)"
-        if ! [[ "$CMAKE_VER" =~ .*"3.21.2".* ]]; then
-          echo "ASSERTION FAILED! Instead of 3.21.2, found: "
+        if ! [[ "$CMAKE_VER" =~ .*"3.22.2".* ]]; then
+          echo "ASSERTION FAILED! Instead of 3.22.2, found: "
           echo "$CMAKE_VER"
           exit -1
         fi
