cmake v3.20.1

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -29,8 +29,8 @@ jobs:
         which cmake
         cmake --version
         CMAKE_VER="$(cmake --version)"
-        if ! [[ "$CMAKE_VER" =~ .*"3.19.2".* ]]; then
-          echo "ASSERTION FAILED! Instead of 3.19.2, found: "
+        if ! [[ "$CMAKE_VER" =~ .*"3.20.1".* ]]; then
+          echo "ASSERTION FAILED! Instead of 3.20.1, found: "
           echo "$CMAKE_VER"
           exit -1
         fi
