CMake -> v3.19.1 Ninja -> v1.10.2

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -29,8 +29,8 @@ jobs:
         which cmake
         cmake --version
         CMAKE_VER="$(cmake --version)"
-        if ! [[ "$CMAKE_VER" =~ .*"3.19.0".* ]]; then
-          echo "ASSERTION FAILED! Instead of 3.19.0, found: "
+        if ! [[ "$CMAKE_VER" =~ .*"3.19.1".* ]]; then
+          echo "ASSERTION FAILED! Instead of 3.19.1, found: "
           echo "$CMAKE_VER"
           exit -1
         fi
@@ -40,8 +40,8 @@ jobs:
         which ninja
         ninja --version
         NINJA_VER="$(ninja --version)"
-        if ! [[ "$NINJA_VER" =~ .*"1.10.1".* ]]; then
-          echo "ASSERTION FAILED! Instead of 1.10.1, found: "
+        if ! [[ "$NINJA_VER" =~ .*"1.10.2".* ]]; then
+          echo "ASSERTION FAILED! Instead of 1.10.2, found: "
           echo "$NINJA_VER"
           exit -1
         fi
